---
- name: Install/update fdm (Linux)
  package:
    name: fdm
    state: latest
  become: true
  when: ansible_system == "Linux"

- name: Install/update fdm (OpenBSD)
  package:
    name: fdm
    state: latest
  become: true
  become_method: doas
  when: ansible_system == "OpenBSD"

- name: Copy fdm.conf over
  template:
    src: "fdm.conf.j2"
    dest: "{{ansible_user_dir}}/.fdm.conf"
    owner: "{{ansible_user_id}}"

- name: Correct permissions
  file:
    path: "{{ansible_user_dir}}/.fdm.conf"
    mode: 0700

