---
- name: Install nginx for Linux
  package:
    name: nginx
    state: latest
  become: true
  when: ansible_system == "Linux"

- include_tasks: nginx.yml
  when: ansible_system == "Linux"

- name: Install nginx for OpenBSD
  package:
    name: nginx--
    state: latest
  become: true
  become_method: doas
  when: ansible_system == "OpenBSD"

- include_tasks: nginx.yml nginx_user=www nginx_group=www nginx_etc_dir_group=wheel
  become_method: doas
  when: ansible_system == "OpenBSD"

