---
- name: "Get dot config files"
  git:
    repo: "https://github.com/weezel/configs.git"
    dest: "{{ansible_user_dir}}/configs"
    clone: yes
    update: yes
    force: no
  tags:
    - getconfigs

- name: "Get script files"
  git:
    repo: "https://github.com/weezel/scripts.git"
    dest: "{{ansible_user_dir}}/scripts"
    clone: yes
    update: yes
    force: no
  tags:
    - getscripts
