---
- hosts: all
  vars_files:
    - vars/packages.yml
    - vars/user.yml
  vars:
    - server_install: false

  roles:
    - {role: set_timezone}
    - {role: default_packages}
    - {role: dotconfigs}
