# Running this playbook:
#   ansible-playbook -v -i localhost, --connection=local ubuntu_desktop.yml
---
- hosts: all
  vars_files:
    - vars/packages.yml
    - vars/user.yml
  vars:
    - server_install: false

  roles:
    # These must be first
    - { role: default_packages }
    - { role: dotconfigs }

    - { role: sleepconfig, tags: sleepconfig }
    - { role: git, tags: git }
    - { role: fstrim, tags: fstrim }
    - { role: xorg_zap, tags: xorg_zap }
    - { role: i3, tags: i3 }
    - { role: xsession, tags: xsession }
    - { role: linux, tags: linux }
    - { role: manjaro, tags: manjaro }
    - { role: ide, tags: ide }

