---
# Needed pre-steps
# 1. Configure doas.conf
# 2. Configure installurl
# 3. Install python 2.7 on the target machine

- hosts: all
  vars_files:
    - vars/network.yml
    - vars/packages.yml
    - vars/openbsd.yml
  vars:
    - server_install: true
    - ip_stub: "192.168.10."
    - common:
        - username: "weezel"
    - network:
        - domain_name: "my.home.lan"

  roles:
    - {role: default_packages}
    - {role: dotconfigs}
    - {role: network/router}
    - {role: apps/dhcpd}
    - {role: apps/unbound}
    - {role: apps/nfsen}
    - {role: network/firewall}
