---
- hosts: servers
  vars:
    - server_install: true
  roles:
    - {role: network/router}
#    - {role: packages, server: true}
#    - {role: apps/dhcpd}
#    - {role: apps/unbound}
#    - {role: apps/pflow}

