---
# Needed pre-steps
# 1. Configure doas.conf
# 2. Configure installurl
# 3. Install python 2.7 on the target machine

- hosts: all
  #vars_files:
  #  - defaults/setup_router
  vars:
    - server_install: true
  roles:
    - {role: default_packages}
    - {role: dotconfigs}
    - {role: network/router}
    - {role: apps/dhcpd}
    - {role: apps/unbound}
    - {role: apps/nfsen}
    - {role: network/firewall}
