---
- hosts: servers
  vars_files:
    - vars/all
  vars:
    - server_install: true
  roles:
#    - {role: default_packages}
#    - {role: network/router}
#    - {role: apps/dhcpd}
#    - {role: apps/unbound}
    - {role: apps/nfsen}
