---
- hosts: all
  vars_files:
    - vars/packages.yml
    - vars/user.yml
  vars:
    - server_install: false

  roles:
    # These must be first
    - { role: default_packages }
    - { role: dotconfigs }

    - { role: git }
    - { role: fstrim }
    - { role: intel_backlight }
    - { role: xorg_zap }
    - { role: i3 }
    - { role: xsession }
