---
- hosts: all
  vars:
    # self-signed or letsencrypt
    - nginx_cert_type: "self-signed"
    - nginx_uwsgi: false
#   - nginx_reverse_proxy: true
    - site_name: "coolsites.lan.local"

  roles:
    - {role: apps/nginx}
#    - {role: apps/php}
