---
- name: Get vether0 MAC
  set_fact:
    vether_mac: "{{ ansible_vether0.macaddress }}"

- name: Dhcpd for {{ network.vether_if[0] }}
  block:
  - name: Enable dhcpd
    command: "rcctl enable dhcpd"
  - name: Configure dhcpd for {{ network.vether_if[0] }} 
    command: "rcctl set dhcpd flags {{ network.vether_if[0] }}"
  become: true
  become_method: doas

- name: Dhcpd for {{ network.vlan_ifs[0] }}
  block:
  - name: Create soft link from dhcpd rc.d
    file:
      src: /etc/rc.d/dhcpd
      dest: /etc/rc.d/dhcpd_vlan100
      state: link
  - name: Enable dhcpd for {{ network.vlan_ifs[0] }}
    command: "rcctl enable dhcpd_vlan100"
  - name: Configure dhcpd for {{ network.vlan_ifs[0] }} 
    command: "rcctl set dhcpd_vlan100 flags {{ network.vlan_ifs[0] }}"
  become: true
  become_method: doas

- name: Upload conf files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: wheel
    mode: 0640
  loop:
    - { src: "dhcpd.conf.j2", dst: "/etc/dhcpd.conf" }
    - { src: "dhcpd_vlan100.conf.j2", dst: "/etc/dhcpd_vlan100.conf" }
  become: true
  become_method: doas
  tags: tada

