---
- include_tasks: manjaro.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: openbsd.yml
  when: ansible_os_family == "OpenBSD"

- include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian" or
        ansible_os_family == "Linuxmint"

