---
- name: "Install common packages"
  openbsd_pkg:
    name: "{{item}}"
    state: latest
  loop: "{{packages.common + packages.obsd_common|flatten(levels=1)}}"
  become: true
  become_method: doas
  tags:
    - packages_common

- name: "Install desktop packages"
  openbsd_pkg:
    name: "{{item}}"
    state: latest
  loop: "{{packages.obsd_desktop|flatten(levels=1)}}"
  become: true
  become_method: doas
  when: not server_install | bool
  tags:
    - packages_desktop

- name: "Install server packages"
  openbsd_pkg:
    name: "{{item}}"
    state: latest
  loop: "{{packages.obsd_server|flatten(levels=1)}}"
  become: true
  become_method: doas
  when: server_install | bool
  tags:
    - packages_server
