---
- name: "Install common packages"
  openbsd_pkg:
    name: "{{item}}"
    state: latest
  with_items:
    - "{{packages.common + packages.obsd_common}}"
  become: true
  become_method: doas
  tags:
    - packages_common

- name: "Install desktop packages"
  openbsd_pkg:
    name: "{{item}}"
    state: latest
  with_items:
    - "{{packages.obsd_desktop}}"
  become: true
  become_method: doas
  when: not server_install | bool
  tags:
    - packages_desktop

- name: "Install server packages"
  openbsd_pkg:
    name: "{{item}}"
    state: latest
  with_items:
    - "{{packages.obsd_server}}"
  become: true
  become_method: doas
  when: server_install | bool
  tags:
    - packages_server
