---
- name: Use old interface names
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
    state: present
  become: true
  register: grub_config_edited

- name: Update grub
  command: update-grub
  become: true
  when: grub_config_edited.changed

