---
- name: "Add {{ user.nickname }} to additional groups"
  user:
    name: "{{ user.nickname }}"
    groups: "{{ item }}"
    append: yes
  loop:
    - dialout
    - sudo
    - wireshark
  become: yes
  when: ansible_system == "Linux"

- name: Configure interface names
  import_tasks: interface_names.yml
