---
- name: "Add {{ user.nickname }} to additional groups"
  user:
    name: "{{ user.nickname }}"
    groups: "{{ item }}"
    append: yes
  loop:
    - dialout
    - docker
    - sudo
  become: yes
  when: ansible_system == "Linux" and distribution is defined and distribution == "Ubuntu"

- name: "Add {{ user.nickname }} to additional groups"
  user:
    name: "{{ user.nickname }}"
    groups: "{{ item }}"
    append: yes
  loop:
    - disk
    - docker
    - uucp
    - wheel
  become: yes
  when: ansible_os_family == "Archlinux"

- name: Configure interface names
  import_tasks: interface_names.yml

- name: Sounds off
  import_tasks: no_sounds.yml

- name: Setup headphone gestures
  import_tasks: headphones.yml
  tags: headphones
