---
- name: Check that blacklist.ips exists for pf.conf
  file:
    path: /etc/blacklist.ips
    state: touch
    owner: root
    group: wheel
    mode: 0664
  become: true

- name: Copy pf.conf template over
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0600
      #validate: pfctl -nf %s # Some of the interfaces aren't up so we cannot do the checks
  become: true

