---
- name: Install fstrim
  package:
    name: util-linux
    state: latest
  become: true
  tags: fstrim

- name: Run fstrim continuously
  ansible.builtin.systemd:
    name: "fstrim.timer"
    enabled: yes
  become: true
  tags: fstrim
