---
- include_tasks: lightdm.yml
  when: ansible_os_family == "Archlinux"

- name: "Copy picom configuration over"
  copy:
    src: picom.conf
    dest: "{{ ansible_user_dir }}/.picom.conf"
    mode: 0600

-  name: "Enable scheduled fstrim"
   become: yes
   ansible.builtin.systemd:
     name: fstrim.timer
     state: started
     enabled: yes

-  name: "Enable pulseaudio for user"
   ansible.builtin.systemd:
     name: pulseaudio
     scope: user
     state: started
     enabled: yes
