---
- name: Copy XSession file (Linux)
  copy:
    src: xsession.desktop
    dest: /usr/share/xsessions
    owner: root
    group: root
    mode: '0744'
  become: yes
  when: ansible_system == "Linux"

- name: Create a soft-link for .xsession file (Linux)
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/configs/xsession_{{ ansible_os_family | lower }}"
    dest: "{{ ansible_user_dir }}/.xsession"
    state: link
  when: ansible_system == "Linux"

