---
- file:
    path: "{{ ansible_user_dir }}/.config/i3"
    mode: 0700
    state: directory

- name: Copy i3 config file over
  copy:
    src: "i3_{{ ansible_os_family | lower }}.config"
    dest: "{{ ansible_user_dir }}/.config/i3/config"

- name: Copy i3status file over
  copy:
    src: "i3status_{{ ansible_os_family | lower }}.conf"
    dest: "{{ ansible_user_dir }}/.i3status.conf"

