---
- name: Create nginx directory under /etc/ssl/
  file:
    path: /etc/ssl/nginx/private
    state: directory
  become: true

- name: Generate a RSA certificate
  command: openssl genrsa -out /etc/ssl/nginx/private/{{site_name}}.key 2048
  args:
    creates: /etc/ssl/nginx/private/{{site_name}}.key
  become: true

- name: Generate Certificate Signing Request (CSR)
  command: >
    openssl req -new -subj "{{ssl_cert_fields}}" \
      -key /etc/ssl/nginx/private/{{site_name}}.key \
      -out /etc/ssl/nginx/private/{{site_name}}.csr
  args:
    creates: /etc/ssl/nginx/private/{{site_name}}.csr
  become: true

- name: Sign the key
  command: >
    openssl x509 -sha256 -req -days "{{ssl.days_valid}}" \
      -in /etc/ssl/nginx/private/{{site_name}}.csr \
      -signkey /etc/ssl/nginx/private/{{site_name}}.key \
      -out /etc/ssl/nginx/{{site_name}}.crt
  args:
    creates: /etc/ssl/nginx/{{site_name}}.crt
  become: true

