---
- name: Copy VSCodium configuration file over
  block:
    - name: Ensure directories exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ ansible_user_dir }}/.config/VSCodium/User"
        - "{{ ansible_user_dir }}/.config/Code - OSS/User"

    - name: Copy VSCode settings over
      ansible.builtin.copy:
        src: "vscodium_config.json"
        dest: "{{ item }}"
      loop:
        - "{{ ansible_user_dir }}/.config/VSCodium/User/settings.json"
        - "{{ ansible_user_dir }}/.config/Code - OSS/User/settings.json"

    - name: Copy VSCode snippets
      ansible.builtin.copy:
        src: "go.json"
        dest: "{{ item }}"
      loop:
        - "{{ ansible_user_dir }}/.config/VSCodium/User/snippets/go.json"
        - "{{ ansible_user_dir }}/.config/Code - OSS/User/snippets/go.json"
  tags:
    - vscodium

- name: PyCharm configurations
  block:
    - name: Ensure PyCharm temporary configuration directory exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/pycharm-settings"
        state: directory

    - name: Copy PyCharm configuration files over
      ansible.builtin.unarchive:
        src: "pycharm_settings.zip"
        dest: "{{ ansible_user_dir }}/pycharm-settings/"
  tags:
    - pycharm
